POST http://localhost:8080/sign-up
Content-Type: application/json

{
    "email":"testemai4withrefl@gmail.com",
    "password": "Test@1234",
    "confirmPassword":"Test@1234",
    "firstName":"Tester",
    "lastName" :"1234!",
    "userName":"wondersmasher",
    "referredBy" :"REF-GO-HMR7EZ"
}